apiVersion: apps/v1
kind: Deployment
metadata:
  name: appidentity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appidentity
  template:
    metadata:
      labels:
        app: appidentity
    spec:
      containers:
      - name: appidentity
        image: loadfms/app-identity:4
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
spec:
  selector:
    app: appidentity
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
